spring:
  datasource:
    url: jdbc:mysql://10.10.10.102:3306/gorany?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: salem
    password: salem
    
  thymeleaf:
    cache: false

server:
  port: 80
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  
  
logging:
  level:
    org.hibernate: debug
    org.springframework: info
    org.salem: debug
